# Generated by Django 6.0.7 on 2026-07-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Repo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repos",
                        to="core.org",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("github_issue", "GitHub issue")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "intake_state",
                    models.CharField(
                        choices=[("received", "Received"), ("dispatched", "Dispatched")],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to="core.org",
                    ),
                ),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signals",
                        to="core.repo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("provisioning", "Provisioning"),
                            ("running", "Running"),
                            ("awaiting_review", "Awaiting review"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=30,
                    ),
                ),
                (
                    "agent_runtime",
                    models.CharField(
                        choices=[("opencode", "OpenCode")], default="opencode", max_length=20
                    ),
                ),
                (
                    "executor_type",
                    models.CharField(
                        choices=[("fake", "Fake"), ("daytona", "Daytona")],
                        default="fake",
                        max_length=20,
                    ),
                ),
                ("sandbox_id", models.CharField(blank=True, max_length=255)),
                ("agent_session_id", models.CharField(blank=True, max_length=255)),
                ("server_password", models.CharField(blank=True, max_length=255)),
                ("branch_name", models.CharField(blank=True, max_length=255)),
                (
                    "result_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pr_opened", "PR opened"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pr_url", models.URLField(blank=True, max_length=500)),
                ("summary", models.TextField(blank=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="core.signal",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.UniqueConstraint(
                fields=("org", "full_name"), name="unique_repo_full_name_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["queued", "provisioning", "running", "awaiting_review"])
                ),
                fields=("signal",),
                name="one_active_run_per_signal",
            ),
        ),
    ]
