# Generated by Django 6.0.7 on 2026-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="pr_merged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
