# Generated by Django 6.0.7 on 2026-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_run_pr_merged_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="agent_base_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
