# Generated by Django 6.0.7 on 2026-07-12 15:24

import django.core.validators
import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_run_agent_base_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="agent_api_key",
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="org",
            name="agent_base_url",
            field=encrypted_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="org",
            name="concurrency_cap",
            field=models.PositiveIntegerField(
                default=3, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="env",
            field=encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="OrgMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")], max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.org",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("org", "user"), name="unique_org_membership")
                ],
            },
        ),
    ]
