# Generated by Django 6.0.7 on 2026-07-12 15:56

import django.db.models.deletion
import django.db.models.fields.json
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_apitoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="base_snapshot",
            field=models.CharField(default="foresight/default", max_length=500),
        ),
        migrations.AddField(
            model_name="repo",
            name="connection_status",
            field=models.CharField(
                choices=[("connected", "Connected"), ("disconnected", "Disconnected")],
                default="connected",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="harness_prompt",
            field=models.TextField(
                default=(
                    "You are Foresight, an autonomous software engineer.\n"
                    "Resolve the supplied signal in the connected repository, test the change, "
                    "and open a pull request.\n"
                )
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="setup_script",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signal",
            name="origin_reference",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="signal",
            name="surface_state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="SurfaceConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("type", models.CharField(choices=[("github", "GitHub")], max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("account_label", models.CharField(max_length=255)),
                ("identity", models.JSONField(default=dict)),
                (
                    "credentials",
                    encrypted_fields.fields.EncryptedJSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surface_connections",
                        to="core.org",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repo",
            name="surface_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repos",
                to="core.surfaceconnection",
            ),
        ),
        migrations.AddField(
            model_name="signal",
            name="origin_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_signals",
                to="core.surfaceconnection",
            ),
        ),
        migrations.AddConstraint(
            model_name="surfaceconnection",
            constraint=models.UniqueConstraint(
                models.F("type"),
                django.db.models.fields.json.KeyTextTransform("installation_id", "identity"),
                name="unique_surface_external_identity",
            ),
        ),
    ]
