# Generated by Django 6.0.7 on 2026-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_repo_base_snapshot_repo_connection_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="failure_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("setup_failed", "Setup failed"),
                    ("sandbox_died", "Sandbox died"),
                    ("agent_error", "Agent error"),
                    ("agent_reported_failed", "Agent reported failed"),
                    ("agent_reported_blocked", "Agent reported blocked"),
                    ("no_result", "No result"),
                    ("canceled", "Canceled"),
                ],
                max_length=40,
            ),
        ),
    ]
