# Generated by Django 6.0.7 on 2026-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_repo_harness_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="setup_verification_output",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="setup_verification_status",
            field=models.CharField(
                choices=[("not_run", "Not run"), ("success", "Success"), ("failed", "Failed")],
                default="not_run",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="snapshot_build_output",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="snapshot_build_status",
            field=models.CharField(
                choices=[("building", "Building"), ("ready", "Ready"), ("failed", "Failed")],
                default="ready",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="snapshot_build_token",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="repo",
            name="snapshot_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="run",
            name="sandbox_archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="session_export_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="repo",
            name="base_snapshot",
            field=models.CharField(default="node:22-bookworm", max_length=500),
        ),
    ]
