# Generated by Django 6.0.7 on 2026-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_repo_setup_verification_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="agent_log_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="run",
            name="setup_log_path",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
